package by.esas.tools.entity

enum class ModuleEnum {
    ACCESS_CONTAINER,
    BASE_DAGGER_UI,
    BASE_UI,
    BIOMETRIC_DECRYPTION,
    CARDLINE,
    CHECKER,
    CUSTOMSWITCH,
    DIALOG,
    DIMEN_UTIL,
    INPUTFIELD_VIEW,
    LISTHEADER,
    LOGGER,
    NUMPAD,
    PIN_VIEW,
    RECYCLER,
    TIMEPARSER,
    TOPBAR_VIEW
}