/*
 * Copyright 2021 Electronic Systems And Services Ltd.
 * SPDX-License-Identifier: Apache-2.0
 */

package by.esas.tools.domain.mapper.error

enum class HttpErrorStatusEnum {
    OK,
    USER_NOT_ACTIVATED,
    WRONG_PASSWORD,
    UNKNOWN_ERROR,
    CODE_INVALID_OR_EXPIRED,
    USER_DOES_NOT_EXIST,
    USER_ALREADY_EXISTS,
    PASSWORD_RECOVERY_FAILED,
    REQUEST_ERROR,
    ACTIVATION_ERROR,
    INVALID_GRANT,

    CLIENT_ERROR,
    SERVER_ERROR,

    EMAIL_TAKEN,
    USER_NAME_TAKEN,
    EMAIL_INVALID,
    USER_NAME_INVALID,
    USER_WITH_LOGIN_EXISTS,
    INCORRECT_PASSWORD_FORMAT,

    UNAUTHORIZED,
    FORBIDDEN,
    ADD_EMAIL_ERROR,
    VERIFY_EMAIL_ERROR,
    DELETE_EMAIL_ERROR,
    ADD_PHONE_ERROR,
    VERIFY_PHONE_ERROR,
    DELETE_PHONE_ERROR,
    UPDATE_PROFILE_ERROR,
    GET_PROFILE_ERROR,
    EMAIL_ALREADY_SET,
    PHONE_NUMBER_NOT_CONFIRMED,
    PHONE_ALREADY_SET,
    EMAIL_NUMBER_NOT_CONFIRMED,
    PHONE_TAKEN,
    REGISTER_ERROR,
    REACTIVATE_ERROR,
    PASSWORD_VALIDATION_ERROR,
    WRONG_PASSWORD_OR_USERNAME,
    ALREADY_ACTIVATED,
    CHECK_ACCOUNT_FAIL,
    UPDATE_USER_ERROR,
    DELETE_USER_ERROR,
    USER_LOCKED_OUT,
    UNAVAILABLE,
    ACCESS_DENIED,
    SCOPE_ERROR
}